# Generated by Django 3.2 on 2021-12-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroidParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('email_contact', models.EmailField(max_length=255)),
                ('advertiser', models.CharField(max_length=255)),
                ('isDone', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Droid Part',
                'verbose_name_plural': 'Droid Parts',
            },
        ),
    ]
